### ISSUE TITLE
The 'Pods-XXX' target has libraries with conflicting names: libwechatsdk.a.

### ISSUE THREAD

**Issue by wjiuxing** [LeoChensj/LeoPayManager#1]
My project has integrated with UMengUShare and a sub-pod 'UMengUShare/Social/WeChat' for a long time. Recently we need to make payment feature in our App. I'd like to use this lib LeoPayManager.
Unfortunately, I run into this issue after running the command 'pod install'.  Yes, I know that the two libs both have used the libwechatsdk. I want to ensure if it is possible to use both UMengUShare and LeoPayManager in our App. Thanks a lot.

Here is my Podfile:

> target :XXX do
> pod 'UMengUShare/UI', '6.2.2'
> pod 'UMengUShare/Social/Sina', '6.2.2'
> pod 'UMengUShare/Social/WeChat', '6.2.2'
> pod 'UMengUShare/Social/QQ', '6.2.2'
> pod 'LeoPayManager', '1.0.0'
> end

**Comment by wjiuxing** [comment]
I eventually dragged the source files into my project directly. So I give up to use cocoapod to maintain the dependence on this lib. Thanks.

**Comment by LeoChensj** [comment]
感谢你的谅解，目前只能先手动导入LeoPayManager，这样的话需要你用cocoapods导入银联、支付宝和Apple Pay，这里我已经做好了，这在cocopods做好了这三个库，分别是UnionPay_SDK_iOS 、Alipay_SDK_iOS 、ApplePay_SDK，然后手动导入LeoPayManager即可，谢谢
